ROLE_USERS_EDITOR = 'Users editor'
ROLE_RECORDS_EDITOR = 'Records editor'
ROLE_API_KEY_EDITOR = 'API key editor'

ROLES = (
    ROLE_USERS_EDITOR,
    ROLE_RECORDS_EDITOR,
    ROLE_API_KEY_EDITOR,
)


IP_FAMILY_IP_v4 = 'ipv4'
IP_FAMILY_IP_v6 = 'ipv6'

IP_FAMILY_VALUES = (
    IP_FAMILY_IP_v4,
    IP_FAMILY_IP_v6,
)
