name: Linters checks, tests and coverage
run-name: Check and tests
on: [push]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          cp .env.ci .env &&
          pip install -r requirements.txt &&
          pip install pycairo

      - name: Run check and test
        run: make check && make lint && make tests

      - name: Code coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov &&
          chmod +x codecov &&
          ./codecov
