name: Check and tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          cp .env.ci .env &&
          pip install -r requirements.txt

      - name: Run check
        run: make check && make lint

      - name: Code coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov &&
          chmod +x codecov &&
          ./codecov
